version: "3"

services:
    databasesql:
      image: mysql:latest
      restart: always
      ports:
      - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: clipsproject
        MYSQL_DATABASE: PHPCLIPS
    adminer:
      image: adminer:latest
      restart: always
      ports:
      - 8080:8080
    rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq_management
      environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=admin
      restart: always